version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  frontend:
  backend:

services:

  prometheus:
    image: prom/prometheus:v2.29.1
    container_name: prometheus.health-timeseries-platform.local
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    ports:
      - 9090:9090
    depends_on:
      - pushgateway
    networks:
      - backend

  grafana:
    image: grafana/grafana:8.0.4
    container_name: grafana.health-timeseries-platform.local
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - backend
      - frontend
